-- soc_system_dbg_ram.vhd

-- Generated using ACDS version 16.0 222

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity soc_system_dbg_ram is
	generic (
		sld_auto_instance_index : string  := "YES";
		sld_instance_index      : integer := 0;
		instance_id             : string  := "RAM0";
		probe_width             : integer := 91;
		source_width            : integer := 0;
		enable_metastability    : string  := "NO"
	);
	port (
		probe : in std_logic_vector(90 downto 0) := (others => '0')  -- probes.probe
	);
end entity soc_system_dbg_ram;

architecture rtl of soc_system_dbg_ram is
	component altsource_probe_top is
		generic (
			sld_auto_instance_index : string  := "YES";
			sld_instance_index      : integer := 0;
			instance_id             : string  := "NONE";
			probe_width             : integer := 1;
			source_width            : integer := 1;
			enable_metastability    : string  := "NO"
		);
		port (
			probe : in std_logic_vector(90 downto 0) := (others => 'X')  -- probe
		);
	end component altsource_probe_top;

begin

	sld_auto_instance_index_check : if sld_auto_instance_index /= "YES" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	sld_instance_index_check : if sld_instance_index /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	instance_id_check : if instance_id /= "RAM0" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	probe_width_check : if probe_width /= 91 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	source_width_check : if source_width /= 0 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	enable_metastability_check : if enable_metastability /= "NO" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	dbg_ram : component altsource_probe_top
		generic map (
			sld_auto_instance_index => "YES",
			sld_instance_index      => 0,
			instance_id             => "RAM0",
			probe_width             => 91,
			source_width            => 0,
			enable_metastability    => "NO"
		)
		port map (
			probe => probe  -- probes.probe
		);

end architecture rtl; -- of soc_system_dbg_ram
