# TCL File Generated by Component Editor 16.0
# Mon Nov 28 17:24:18 BRST 2016
# DO NOT MODIFY


# 
# ogpu_manager "ogpu_manager" v1.0
# Fabricio 2016.11.28.17:24:18
# ogpu_manager
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module ogpu_manager
# 
set_module_property DESCRIPTION ogpu_manager
set_module_property NAME ogpu_manager
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP OGPU_TEST
set_module_property AUTHOR Fabricio
set_module_property DISPLAY_NAME ogpu_manager
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ogpu_manager
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file ogpu_manager.vhd VHDL PATH ogpu_manager.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset_sink_reset reset Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_sink
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_sink_reset reset Input 1


# 
# connection point dma_command
# 
add_interface dma_command avalon start
set_interface_property dma_command addressUnits SYMBOLS
set_interface_property dma_command associatedClock clock_sink
set_interface_property dma_command associatedReset reset_sink
set_interface_property dma_command bitsPerSymbol 8
set_interface_property dma_command burstOnBurstBoundariesOnly false
set_interface_property dma_command burstcountUnits WORDS
set_interface_property dma_command doStreamReads false
set_interface_property dma_command doStreamWrites false
set_interface_property dma_command holdTime 0
set_interface_property dma_command linewrapBursts false
set_interface_property dma_command maximumPendingReadTransactions 0
set_interface_property dma_command maximumPendingWriteTransactions 0
set_interface_property dma_command readLatency 0
set_interface_property dma_command readWaitTime 1
set_interface_property dma_command setupTime 0
set_interface_property dma_command timingUnits Cycles
set_interface_property dma_command writeWaitTime 0
set_interface_property dma_command ENABLED true
set_interface_property dma_command EXPORT_OF ""
set_interface_property dma_command PORT_NAME_MAP ""
set_interface_property dma_command CMSIS_SVD_VARIABLES ""
set_interface_property dma_command SVD_ADDRESS_GROUP ""

add_interface_port dma_command avm_m0_address address Output 8
add_interface_port dma_command avm_m0_read read Output 1
add_interface_port dma_command avm_m0_waitrequest waitrequest Input 1
add_interface_port dma_command avm_m0_readdata readdata Input 32
add_interface_port dma_command avm_m0_write write Output 1
add_interface_port dma_command avm_m0_writedata writedata Output 32


# 
# connection point host_control
# 
add_interface host_control avalon end
set_interface_property host_control addressUnits WORDS
set_interface_property host_control associatedClock clock_sink
set_interface_property host_control associatedReset reset_sink
set_interface_property host_control bitsPerSymbol 8
set_interface_property host_control bridgedAddressOffset 0
set_interface_property host_control burstOnBurstBoundariesOnly false
set_interface_property host_control burstcountUnits WORDS
set_interface_property host_control explicitAddressSpan 0
set_interface_property host_control holdTime 0
set_interface_property host_control linewrapBursts false
set_interface_property host_control maximumPendingReadTransactions 0
set_interface_property host_control maximumPendingWriteTransactions 0
set_interface_property host_control readLatency 0
set_interface_property host_control readWaitTime 1
set_interface_property host_control setupTime 0
set_interface_property host_control timingUnits Cycles
set_interface_property host_control writeWaitTime 0
set_interface_property host_control ENABLED true
set_interface_property host_control EXPORT_OF ""
set_interface_property host_control PORT_NAME_MAP ""
set_interface_property host_control CMSIS_SVD_VARIABLES ""
set_interface_property host_control SVD_ADDRESS_GROUP ""

add_interface_port host_control avs_s0_address address Input 8
add_interface_port host_control avs_s0_read read Input 1
add_interface_port host_control avs_s0_readdata readdata Output 32
add_interface_port host_control avs_s0_write write Input 1
add_interface_port host_control avs_s0_writedata writedata Input 32
add_interface_port host_control avs_s0_waitrequest waitrequest Output 1
set_interface_assignment host_control embeddedsw.configuration.isFlash 0
set_interface_assignment host_control embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment host_control embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment host_control embeddedsw.configuration.isPrintableDevice 0

