# TCL File Generated by Component Editor 16.0
# Mon Nov 28 16:55:38 BRST 2016
# DO NOT MODIFY


# 
# quad_data_gen "quad_data_gen" v1.0
# Fabricio 2016.11.28.16:55:38
# quad_data_gen
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module quad_data_gen
# 
set_module_property DESCRIPTION quad_data_gen
set_module_property NAME quad_data_gen
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP OGPU_TEST
set_module_property AUTHOR Fabricio
set_module_property DISPLAY_NAME quad_data_gen
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL quad_data_gen
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file quad_data_gen.vhd VHDL PATH ogpu_test_data_generator/quad_data_gen.vhd TOP_LEVEL_FILE


# 
# documentation links
# 
add_documentation_link untitled http://


# 
# parameters
# 
add_parameter random BOOLEAN true ""
set_parameter_property random DEFAULT_VALUE true
set_parameter_property random DISPLAY_NAME random
set_parameter_property random WIDTH ""
set_parameter_property random TYPE BOOLEAN
set_parameter_property random UNITS None
set_parameter_property random DESCRIPTION ""
set_parameter_property random AFFECTS_GENERATION false
add_parameter initial_value NATURAL 0 ""
set_parameter_property initial_value DEFAULT_VALUE 0
set_parameter_property initial_value DISPLAY_NAME initial_value
set_parameter_property initial_value WIDTH ""
set_parameter_property initial_value TYPE NATURAL
set_parameter_property initial_value UNITS None
set_parameter_property initial_value ALLOWED_RANGES 0:2147483647
set_parameter_property initial_value DESCRIPTION ""
set_parameter_property initial_value AFFECTS_GENERATION false


# 
# display items
# 


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset reset_sink
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end addr address Input 3
add_interface_port conduit_end req request Input 1
add_interface_port conduit_end data data Output 32
add_interface_port conduit_end ready ready Output 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock_sink_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset_sink_reset reset Input 1

